version: '3.8'

services:
  sbsc_redis:
    container_name: sbsc_redis
    image: redis:6.2.6-alpine
    restart: on-failure
    environment:
      REDIS_PASSWORD:
    volumes:
      - sbsc_redis:/data
    ports:
      - '6379:6379'
    extra_hosts:
      - 'host.docker.internal:host-gateway'

volumes:
  sbsc_redis:
